sudo: required
dist: trusty
language: python

python:
  - 2.7

env:
  - DJANGO_VERSION=1.8.19
  - DJANGO_VERSION=1.11.11

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install .

before_script:
  - cd tests

script: make tests
