sudo: required
dist: trusty
language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.11.11

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q Pillow
  - pip install -q sorl-thumbnail
  - pip install -q django_thumbor
  - pip install .

before_script:
  - cd tests

script: make coverage

after_script: coveralls
