sudo: required
dist: xenial
language: python

matrix:
  include:
  - python: 3.6
    env: DJANGO_VERSION=1.11.29
  - python: 3.6
    env: DJANGO_VERSION=2.0.13
  - python: 3.6
    env: DJANGO_VERSION=2.1.15
  - python: 3.6
    env: DJANGO_VERSION=2.2.11
  - python: 3.6
    env: DJANGO_VERSION=3.0.4
  - python: 3.6
    env: DJANGO_VERSION=3.1.14

install:
  - pip install -q Django==$DJANGO_VERSION
  - pip install -q coverage
  - pip install -q coveralls
  - pip install -q Pillow
  - pip install -q sorl-thumbnail
  - pip install -q django_thumbor
  - pip install .

before_script:
  - cd tests

script: make coverage

after_script: coveralls
